/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kjs' at '16. 4. 1 오전 10:35' with Gradle 2.11
 *
 * @author kjs, @date 16. 4. 1 오전 10:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
